# Server Setting
server:
  port: 10600

spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false

  # Redis Setting
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

  # DB Connection Setting
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 1000 # 컬렉션들의 레이지 로딩 발생 시 컬렉션 중 하나의 프록시에서 lazy 로딩이 호출되도 모든 컬렉션을 in 쿼리로 한번에 조회
    open-in-view: false

# Logging Setting
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG

# configuration properties
account:
  client-id: nuguri
  client-secret: bom
  redirect-uri: http://localhost:9600/main
  admin-email: admin@naver.com
  admin-password: 1234
  user-email: user@naver.com
  user-password: 1234
  check-token-url: http://localhost:9600/oauth/check_token
  revoke-token-url: http://localhost:9600/oauth/revoke_token
  access-token-url: http://localhost:9600/oauth/token
  authorize-code-url: http://localhost:9600/oauth/authorize

