# Server Setting
server:
  port: 8600

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9600/oauth

spring:
  #  jackson:
  #    deserialization:
  #      FAIL_ON_UNKNOWN_PROPERTIES: true # 불필요한 데이터 바인딩 시 직렬화 하지 않고 에러 발생시킴

  # DB Connection Setting
  datasource:
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
#    open-in-view: false

# Logging Setting
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG

# configuration properties
auth:
  client-id: nuguri
  client-secret: bom
  remote-server-url: http://localhost:9600/oauth/check_token