# Server Setting
server:
  port: 9600

spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false

  # Redis Setting
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

  # DB Connection Setting
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

# Logging Setting
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG

# configuration properties
auth:
  client-id: nuguri
  client-secret: bom
  redirect-uri: http://localhost:${server.port}/main
  admin-email: admin@naver.com
  admin-password: 1234
  user-email: user@naver.com
  user-password: 1234
