# Server Setting
server:
  port: 7600
  servlet:
    session:
      cookie:
        name: client-session-id

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false

  # DB Connection Setting
  datasource:
    url: jdbc:mysql://localhost:3306/client?serverTimezone=UTC&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

# Logging Setting
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
#      springframework:
#        security: DEBUG

# properties
oauth:
  nuguri:
    loginUrl: "http://localhost:9600/oauth/authorize"
    tokenUrl: "http://localhost:9600/oauth/token"
    infoUrl: "http://localhost:9600/oauth/me"
    clientId: "07e879ba-2e23-4fcb-a794-7017c4984517"
    clientSecret: "447f2e88-ff7a-4004-ae00-f50d3d6d58f3"
    redirectUri: "http://localhost:7600/nuguri/login"